#!/usr/bin/env python3
"""A validation metric that can actually detect a change. The old one cannot.

THE PROBLEM. Four structural corrections in a row -- screening 22 non-human /
non-case-control papers, splitting rank placeholders off their parents, and now
restricting to gut evidence -- each reported "zero decisive pairs flipped,
McNemar exact p = 1.00", and each was written up as a strong empirical null
("not underpowered -- a true zero").

They are not empirical nulls. They are a tautology of the test.

  A pair counts as "decisive" only when our edge is NOT contested, and
  `contested = bool(n_up and n_down)`. So every decisive edge is UNANIMOUS --
  verified: all 1,765 non-contested edges have a minority vote of exactly 0.
  Every one of these corrections only ever REMOVES papers (or moves them to a
  new node key, which leaves the pair out of the "decisive in both" set). A
  unanimous edge that loses papers stays unanimous in the same direction.

  Therefore no pair decisive in both variants can ever flip, for any
  paper-removal correction whatsoever. The zero was guaranteed before any data
  was collected, and the p-value of 1.00 is not evidence of no effect.

Empirically this is exactly what happens: across the gut restriction, 17 edges
change `direction`, and every single one is a contested<->decisive transition.
Not one is enriched<->depleted.

THE FIX. Stop thresholding our evidence into a unanimous/contested binary before
comparing. Score the pair on the SIGNED STRENGTH of our evidence:

    s = (n_up - n_down) / (n_up + n_down)   in [-1, +1]
    c = s * r                                r = +1/-1, the reference direction

`c` is +1 when every paper we have agrees with the curated database, -1 when
every paper contradicts it, and moves continuously in between. Dropping one oral
paper from a 12-up/1-down edge moves that edge's c from 0.846 to 1.0 -- a change
the binary metric is blind to by construction.

THE TEST. Two variants are compared on the pairs present in both, and the null is
generated by PAPER-LEVEL resampling: drop the same NUMBER of papers at random and
recompute the change, many times. That is the right null because observations are
not independent -- one paper contributes to many pairs -- and because it asks the
question that matters: is the non-gut evidence unusual, or is any six papers?

    python agreement_metric.py --drop nongut     # the 6 non-gut papers
    python agreement_metric.py --drop screened   # the 22 the MAIN_DATA screen removed
"""
import argparse
import json
import os


from collections import defaultdict

import numpy as np

from validate_external import DISEASE_MAP, OUTCOME, load_disbiome, load_peryton

HERE = os.path.dirname(os.path.abspath(__file__))
GUT = {"stool", "gut biopsy"}


def reference(records, tax):
    """-> {(taxid, disease): +1 / -1} for references with a decisive direction."""
    ref = defaultdict(lambda: defaultdict(int))
    for r in records:
        our = DISEASE_MAP.get(r["disease"].lower())
        out = OUTCOME.get(r["outcome"].lower())
        if not (our and out and r["microbe"]):
            continue
        tid, *_ = tax.resolve(r["microbe"])
        if tid:
            ref[(tid, our)][out] += 1
    out = {}
    for k, v in ref.items():
        if v["enriched"] != v["depleted"]:
            out[k] = 1 if v["enriched"] > v["depleted"] else -1
    return out


def paper_votes(rows, tax):
    """[(title, [(taxid, disease, +1/-1), ...]), ...] -- parsed ONCE.

    Rebuilding graph.json per permutation would be minutes per thousand draws.
    The concordance only needs each paper's (taxon, disease, direction) votes, so
    they are resolved once through the same build_kg normalisers the real graph
    uses -- placeholder splitting included -- and permutations just re-aggregate.
    """
    import build_kg as B
    B.SPLIT_PLACEHOLDERS = True
    out = []
    for r in rows:
        disease, _ = B.norm_disease(r.get("predicted_disease") or r.get("disease") or "")
        votes = []
        for d, col in ((1, "predicted_enriched"), (-1, "predicted_depleted")):
            for raw in B.parse_taxa(r.get(col)):
                key, *_ = B.norm_taxon(raw, tax)
                if key.startswith("ncbi:"):
                    votes.append((key.split(":", 1)[1], disease, d))
        out.append((r.get("title", ""), votes))
    return out


def concordance(votes, ref, exclude=frozenset()):
    """-> {(taxid, disease): c}, the signed concordance of our evidence.

    One paper naming a taxon twice is still one vote, matching build_kg.py.
    """
    seen = defaultdict(set)
    tally = defaultdict(lambda: [0, 0])
    for title, vs in votes:
        if title in exclude:
            continue
        for tid, disease, d in vs:
            k = (tid, disease)
            if k not in ref or (title, d) in seen[k]:
                continue
            seen[k].add((title, d))
            tally[k][0 if d > 0 else 1] += 1
    out = {}
    for k, (up, dn) in tally.items():
        n = up + dn
        if n:
            out[k] = ((up - dn) / n) * ref[k]
    return out


def verify_against_graph(votes, exclude=frozenset(), graph_path=None):
    """The in-memory tally MUST equal the committed graph, or the shortcut is a bug.

    Skipping the rebuild is only legitimate if it produces the same counts the
    real builder does. This checks every taxid-keyed edge's n_up/n_down against
    graph.json and refuses to continue on any mismatch.
    """
    G = json.load(open(graph_path or os.path.join(HERE, "graph.json")))
    want = {(e["taxon_key"].split(":", 1)[1], e["disease"]): (e["n_up"], e["n_down"])
            for e in G["edges"] if e["taxon_key"].startswith("ncbi:")}
    seen = defaultdict(set)
    got = defaultdict(lambda: [0, 0])
    for title, vs in votes:
        if title in exclude:
            continue
        for tid, disease, d in vs:
            k = (tid, disease)
            if (title, d) in seen[k]:
                continue
            seen[k].add((title, d))
            got[k][0 if d > 0 else 1] += 1
    got = {k: tuple(v) for k, v in got.items()}
    bad = [k for k in set(want) | set(got) if want.get(k) != got.get(k)]
    if bad:
        raise SystemExit(f"in-memory tally does NOT match graph.json on {len(bad)} "
                         f"edges, e.g. {bad[:5]} "
                         f"(graph {[want.get(k) for k in bad[:5]]} vs "
                         f"here {[got.get(k) for k in bad[:5]]})")
    print(f"  verified: in-memory tally matches graph.json on all {len(want)} "
          f"taxid-keyed edges")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--iters", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--drop", choices=["nongut", "screened", "dedup"], default="nongut",
                    help="which paper-removal correction to test: the 6 non-gut "
                         "papers, the 22 non-human / non-case-control papers "
                         "the MAIN_DATA screen removed, or the 12 duplicate paper "
                         "copies (the same paper scraped under two links)")
    ap.add_argument("--out", default="agreement_metric.json",
                    help="result file (do not clobber a previous correction's)")
    a = ap.parse_args()
    rng = np.random.default_rng(a.seed)

    if a.drop == "nongut":
        site = {t: v["site"] for t, v in
                json.load(open(os.path.join(HERE, "body_site.json")))["papers"].items()}
        rows = json.load(open(os.path.join(HERE, "extractions_screened.json")))
        drop = [r["title"] for r in rows
                if site.get(r.get("title"), "unknown") not in GUT
                and site.get(r.get("title")) is not None]
        # graph.json is the all-sites graph, i.e. the BEFORE side here.
        verify_side = "before"
        label = ("all_sites", "gut_only")
    elif a.drop == "dedup":
        # The same paper scraped twice under a PubMed and a PMC/publisher link.
        # NOTE the null is deliberately mismatched and therefore CONSERVATIVE:
        # it drops 12 RANDOM papers, deleting their evidence outright, whereas
        # deduplication deletes only redundant evidence -- the twin still votes.
        # So the null's spread is an upper bound on what this correction could
        # move, and a small observed change here is expected, not reassuring.
        import build_kg as BK
        rows = json.load(open(os.path.join(HERE, "extractions_screened.json")))
        _, dropped_rows = BK.dedup_rows(rows, verbose=False)
        drop = [r["title"] for r in dropped_rows]
        # graph.json is the DEDUPED graph now that the fix is committed, so it is
        # the AFTER side. (It was the before side only while duplicates were still
        # in the shipped graph; the verify guard caught the switch rather than
        # silently scoring against the wrong baseline.)
        verify_side = "after"
        label = ("with_dupes", "deduped")
    else:
        # The 348-row set, before the screen removed 22 papers. Cache scope was
        # checked: only 4 of the 22 produce any taxa at all, and their only three
        # cache misses are misspellings ("Eisenbergiela tayi") the real taxdump
        # would not resolve either -- so the replay cache does not bias this.
        rows = json.load(open(os.path.join(HERE, "extractions_corrected.json")))
        screen = json.load(open(os.path.join(HERE, "maindata_screen.json")))
        drop = [t for t, v in screen.items() if v["category"] != "KEEP"]
        verify_side = "after"
        label = ("all348", "screened")
    print(f"papers: {len(rows)} rows, dropping {len(drop)} ({a.drop})")

    from taxonomy_cache import load_taxonomy
    tax = load_taxonomy()

    votes = paper_votes(rows, tax)
    dropset = frozenset(drop)
    # graph.json is the committed graph: the BEFORE side for the body-site test,
    # the AFTER side for the screen. Whichever it is must reproduce exactly, or
    # the in-memory shortcut is not faithful and nothing below can be trusted.
    verify_against_graph(votes, exclude=dropset if verify_side == "after" else frozenset())

    results = []
    for name, recs in (("Disbiome", load_disbiome()[0]), ("Peryton", load_peryton()[0])):
        if recs is None:
            continue
        ref = reference(recs, tax)
        A, B = concordance(votes, ref), concordance(votes, ref, dropset)
        lab_a, lab_b = label
        common = sorted(set(A) & set(B))
        obs = float(np.mean([B[k] - A[k] for k in common]))
        base = float(np.mean([A[k] for k in common]))

        print("\n" + "=" * 78)
        print(f"{name.upper()}   pairs scored in both variants: {len(common)}")
        print("=" * 78)
        print(f"  mean concordance, {lab_a:10}: {base:+.4f}")
        print(f"  mean concordance, {lab_b:10}: {base+obs:+.4f}")
        print(f"  observed change             : {obs:+.4f}")
        moved = [k for k in common if abs(B[k] - A[k]) > 1e-12]
        print(f"  pairs whose score moved at all: {len(moved)} of {len(common)}"
              f"  (the binary metric saw 0)")

        # --- paper-level null: drop the same NUMBER of papers at random --------
        null = []
        pool = [t for t in {r["title"] for r in rows} if t not in dropset]
        for _ in range(a.iters):
            gone = frozenset(rng.choice(pool, size=len(drop), replace=False))
            Bx = concordance(votes, ref, gone)
            ks = [k for k in common if k in Bx]
            null.append(np.mean([Bx[k] - A[k] for k in ks]) if ks else 0.0)
        null = np.array(null)
        p = float((np.abs(null) >= abs(obs) - 1e-12).mean())
        print(f"  paper-level null ({a.iters} draws of {len(drop)} random papers):")
        print(f"    null mean {null.mean():+.4f}, SD {null.std():.4f}, "
              f"|null| 95th pct {np.percentile(np.abs(null),95):.4f}")
        print(f"    two-sided p = {p:.3f}")
        print(f"    minimum detectable |change| at this n ~ "
              f"{np.percentile(np.abs(null),95):.4f}")
        results.append({"source": name, "correction": a.drop, "n_pairs": len(common), "n_moved": len(moved),
                        "baseline": round(base, 4), "observed_change": round(obs, 4),
                        "null_sd": round(float(null.std()), 4),
                        "min_detectable": round(float(np.percentile(np.abs(null), 95)), 4),
                        "p": round(p, 4), "iters": a.iters, "n_dropped": len(drop)})

    json.dump(results, open(os.path.join(HERE, a.out), "w"), indent=1)
    print(f"\nwrote {a.out}")


if __name__ == "__main__":
    main()
